
hello: hello.c 
	gcc hello.c -o hello
	chmod +x hello
	rm hello
	
compare: compare.c 
	gcc compare.c -o compare
	chmod +x compare.c
	./compare
	rm compare


meow: meow.c
	gcc meow.c -o meow
	chmod +x meow.c 
	./meow 
	rm meow
